### ISSUE TITLE
size in kriging initiate

### ISSUE THREAD

**Issue by dperkins1234** [Rafnuss-PhD/SGS#3]
Hi there,

Just to let you know that using matlab 2017 the programmes do not run because of an error in the kriging initiate function:

the: if size(covar.range0) ==1 requires changing to if numel(covar.range0) == 1 etc. for the programme to run.

Thanks,
Duncan

**Comment by TimurMZh** [comment]
Hi dperkins1234,

Good note!
I did it by length().

Timur

**Comment by Rafnuss** [comment]
Thanks for reporting this error. Let me know if you still have other(s) issue(s)
